// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZlHh-X5vGABeCjWqYZ_v80ZBTA5W3_wE',
    appId: '1:189806516611:web:7a0ea541a71709b54efeb6',
    messagingSenderId: '189806516611',
    projectId: 'todo-app-e15c8',
    authDomain: 'todo-app-e15c8.firebaseapp.com',
    storageBucket: 'todo-app-e15c8.firebasestorage.app',
    measurementId: 'G-M08TCJEKJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MUKqBZQHAVNVcHTB2BFC6tQlNj5hvzE',
    appId: '1:189806516611:android:9855ef74214f614e4efeb6',
    messagingSenderId: '189806516611',
    projectId: 'todo-app-e15c8',
    storageBucket: 'todo-app-e15c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVgg2hf8uWa1XRgSNF_lzgOaMQUnOZawk',
    appId: '1:189806516611:ios:7e0c54b5dbeee8934efeb6',
    messagingSenderId: '189806516611',
    projectId: 'todo-app-e15c8',
    storageBucket: 'todo-app-e15c8.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVgg2hf8uWa1XRgSNF_lzgOaMQUnOZawk',
    appId: '1:189806516611:ios:7e0c54b5dbeee8934efeb6',
    messagingSenderId: '189806516611',
    projectId: 'todo-app-e15c8',
    storageBucket: 'todo-app-e15c8.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZlHh-X5vGABeCjWqYZ_v80ZBTA5W3_wE',
    appId: '1:189806516611:web:c60a479c52208aa94efeb6',
    messagingSenderId: '189806516611',
    projectId: 'todo-app-e15c8',
    authDomain: 'todo-app-e15c8.firebaseapp.com',
    storageBucket: 'todo-app-e15c8.firebasestorage.app',
    measurementId: 'G-R0VLDSXENZ',
  );
}
